name: Trigger Webhook on Pull Request Merge or Close
on:
  pull_request:
    types:
      - closed
    branches:
      - main # specify the branches you want to trigger the webhook on (e.g., main, master)

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Trigger Webhook
        run: |
          # Replace 'YOUR_WEBHOOK_URL' with the actual URL where you want to send the webhook request
          curl -X POST -H "Content-Type: application/json" -d '{"event_type": "pull_request_closed_or_merged"}' http://3.23.6.46:8080/github-webhook/
